### ISSUE TITLE
Stuck at: Opening drive

### ISSUE THREAD

**Issue by rugk** [markusfisch/Sojuz404#1]
I'm stuck at the following position:
* In my dream I asked the mechanic for how to open the drive and found it in the room there, which is just an example as it seems.
  ![image](https://user-images.githubusercontent.com/11966684/104650070-f5edbe00-56b5-11eb-8456-79f62f167021.png)
* I got back and outside, clicked the "_grey flasp_" there, but I have 8 boxes that change colors. I have tried to make them the same color, but that did not work.

I don't know what to do.
Going back and forth between my dream and the drive does show anything new. No one seems to tell me something new.

Firefox 84

**Comment by markusfisch** [comment]
The colored boxes represent the mathematical operations of the formula on the slate. The formula, the Professor and Vitali, the engineer, have different opinions about. The Professor is right, of course 😉 But Vitali built the drive and so one of the operations is wrong, i.e. has the wrong color.

So you need to change just _one_ box.

Blue is multiplication, green addition, red substraction and yellow division. As soon as you have the right combination, a message will appear.

If you still don't know what to do, this [ROT13](https://en.wikipedia.org/wiki/ROT13) enciphered string will tell you the answer: `Gur ynfg obk zhfg or erq` 😉

**Comment by rugk** [comment]
> The colored boxes represent the mathematical operations of the formula on the slate. 

Wooooah… this is a thing one has to hit on first :laughing: 

But thanks for the tip! :D

**Comment by rugk** [comment]
Ahh, now I also see multiple rows when playing it again. IIRC the last time I only had 8 boxes _in one row_…

Nevermind, in any case I got the message now and it looks all right:

<details>
<summary>Spoiler!</summary>

![grafik](https://user-images.githubusercontent.com/11966684/104728336-098d3900-5737-11eb-95e4-a4a50e1b6d94.png)


</details>
Aand yay, finished! Hehe, quite funny if you get to that point. :smile:

**Comment by markusfisch** [comment]
The one with 8 boxes in a row is the original game as it was submitted to @js13kgames.

But since quite a few people got stuck there, I changed the layout to better reflect the formula. So it depends on which link you use to start the game 😉 The link from here, from GitHub, is the post-compo version with the improved layout.

**Comment by rugk** [comment]
Ohhh okay… :upside_down_face:  Thanks for the explanation!
